name: Lint

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 7 * * *'

jobs:
  Linters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements_dev.txt
          pre-commit install

      - name: Lint
        run:  pre-commit run --all-files
