name: Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'docusaurus/**'
  schedule:
    - cron: '0 7 * * *'

jobs:
  Unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y gdal-bin
          sudo apt install -y libgdal-dev
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          pip install .
          pip install coverage
          pip uninstall --yes gdal
          pip install numpy
          pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"

      - name: Run All Unittest
        run: coverage run -m unittest

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
